# Generated by Django 4.2.7 on 2026-03-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender_upi', models.CharField(max_length=128)),
                ('receiver_upi', models.CharField(max_length=128)),
                ('sender_bank', models.CharField(blank=True, max_length=64)),
                ('receiver_name', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('device_id', models.CharField(blank=True, max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('is_fraud', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('fraud', 'Fraud'), ('review', 'Under Review')], default='safe', max_length=16)),
                ('flags', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
