# Generated by Django 4.2.7 on 2026-03-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frauds', '0003_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('safe', 'Safe'), ('fraud', 'Fraud'), ('suspicious', 'Suspicious'), ('review', 'Under Review')], default='safe', max_length=16),
        ),
    ]
